[package]
name = "build_your_own_lisp_in_rust"
version = "0.1.0"
authors = [" <armor_hiking@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
